remote_theme: daattali/beautiful-jekyll@6.0.1
title: Hassan Berry
author: Hassan Berry

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"

################
# --- Logo --- #
################

avatar: "/images/hassan.jpeg"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "hassan.berry2013@gmail.com"
  linkedin: in/hassan-berry
  github: gwenfutapics  # Replace with your actual GitHub username

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "gwenfutapics.github.io"  # Replace with your GitHub Pages URL
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

#keywords: "data,health,science,electrical,engineering,analytics"

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
